name: mn_lottery_demo
description: "Minnesota Lottery mobile app mini-prototype (interview demo). NOT an official app."
publish_to: "none"
version: 0.1.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.5.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.4
  firebase_messaging: ^15.0.1
  firebase_analytics: ^11.2.1
  google_sign_in: ^6.2.1
  go_router: ^14.2.0
  url_launcher: ^6.3.2
  google_fonts: ^6.3.1
  scratcher: ^2.5.0
dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/lucky7.png
    - assets/images/bird_logo.jpg
